ALTER TABLE videos ADD COLUMN hls_url VARCHAR(500);
ALTER TABLE videos ADD COLUMN is_hls_ready BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE videos ADD COLUMN resolution VARCHAR(50);
ALTER TABLE videos ADD COLUMN bitrate INT;
