CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    phone VARCHAR(11) NULL UNIQUE COMMENT '手机号',
    email VARCHAR(100) NULL UNIQUE COMMENT '邮箱',
    password VARCHAR(255) NOT NULL COMMENT 'BCrypt加密密码',
    status ENUM('ACTIVE', 'BANNED', 'DELETED') NOT NULL DEFAULT 'ACTIVE' COMMENT '账号状态',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CONSTRAINT chk_phone_or_email CHECK (phone IS NOT NULL OR email IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=204626;


CREATE TABLE profiles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE COMMENT '用户ID',
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户昵称',
    avatar_url VARCHAR(500) NULL COMMENT '头像URL',
    bio TEXT NULL COMMENT '个人简介',
    gender ENUM('MALE', 'FEMALE', 'OTHER') NULL COMMENT '性别',
    birthday DATE NULL COMMENT '生日',
    level INT NOT NULL DEFAULT 1 COMMENT '用户等级',
    coins INT NOT NULL DEFAULT 0 COMMENT '硬币数',
    followers_count INT NOT NULL DEFAULT 0 COMMENT '粉丝数',
    following_count INT NOT NULL DEFAULT 0 COMMENT '关注数',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CONSTRAINT fk_user_profile_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
